coverage:
  require_ci_to_pass: false
  status:
    project:
      default:
        target: auto
        threshold: 5%
        paths:
          - src/cicd
    patch:
      default:
        target: 60%

ignore:
  - tests
