require_relative ".cocoapods/hooks"

platform :ios, "14.0"
use_frameworks!

target "EX" do
  target "EXTests" do
    inherit! :search_paths
    # Pods for testing
  end

  target "EXUITests" do
    # Pods for testing
  end
end

post_install do |installer|
  hooks = [
    Pod::XCConfigsHook.new(installer: installer),
  ]
  hooks.each(&:run)
end
