name: deploy

on:
  workflow_dispatch:
    inputs:
      deploy-rc:
        description: Deploy a RC version
        type: boolean
      deploy-stable:
        description: Deploy a stable version
        type: boolean

jobs:
  deploy-pypi-rc:
    name: Deploy (RC)
    if: ${{ inputs.deploy-rc }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Exec
        uses: trinhngocthuyen/gh-action-py-exec@main
        with:
          hook-version-file: VERSION
          hook-version-suffix: .rc${{ github.run_id }}
          pypi-token: ${{ secrets.PYPI_TOKEN }}

  deploy-pypi-stable:
    name: Deploy (stable)
    if: ${{ inputs.deploy-stable }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Exec
        uses: trinhngocthuyen/gh-action-py-exec@main
        with:
          pypi-token: ${{ secrets.PYPI_TOKEN }}
