name: deploy

on:
  workflow_dispatch:
    inputs:
      pypi_release_type:
        description: Deploy to PyPI
        type: choice
        required: false
        options:
          - rc
          - stable

jobs:
  deploy-pypi:
    name: Deploy to PyPI (${{ matrix.release_type }})
    runs-on: ubuntu-latest
    if: ${{ inputs.pypi_release_type }} == ${{ matrix.release_type }}
    strategy:
      matrix:
        include:
          - release_type: rc
            version_suffix: .rc${{ github.run_id }}
          - release_type: stable
            version_suffix: ''
    environment: production
    steps:
      - name: Exec
        uses: trinhngocthuyen/gh-action-py-exec@main
        with:
          hook-version-file: VERSION
          hook-version-suffix: .rc${{ github.run_id }}
          pypi-token: ${{ secrets.PYPI_TOKEN }}
