name: eng-workflow

on:
  workflow_dispatch:
    inputs:
      bump-version:
        description: Bump version
        type: boolean

env:
  PYTHON_VERSION: '3.10'

jobs:
  bump-version:
    if: ${{ inputs.bump-version }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Install
        uses: trinhngocthuyen/gh-actions/py/install@main
      - name: Bump version
        uses: trinhngocthuyen/gh-actions/core/bump_version@main
        with:
          version-file: VERSION
      - name: Push changes
        uses: trinhngocthuyen/gh-actions/git/push@main
        with:
          commit_msg: "CHORE: Bump version"
          token: ${{ secrets.GH_TOKEN }}
