name: integration-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-12 # https://github.com/actions/virtual-environments (xcode 13.4.1)
    steps:
      - name: Install
        uses: trinhngocthuyen/gh-actions/py/install@main
      - name: Makefile
        uses: trinhngocthuyen/gh-actions/core/makefile@main
        with:
          targets: install test.integration.ios ACTION=build
      - name: Upload artifacts
        uses: trinhngocthuyen/gh-actions/core/artifacts@main
        with:
          artifacts-upload-name: build
          artifacts-upload-path: examples/ios/DerivedData/Build/Products

  test:
    runs-on: macos-12
    needs: build
    strategy:
      matrix:
        idx: [1, 2]
    steps:
      - name: Install
        uses: trinhngocthuyen/gh-actions/py/install@main
      - name: Download artifacts
        uses: trinhngocthuyen/gh-actions/core/artifacts@main
        with:
          artifacts-download-name: build
          artifacts-download-path: examples/ios/DerivedData/Build/Products
      - name: Makefile
        uses: trinhngocthuyen/gh-actions/core/makefile@main
        with:
          targets: install test.integration.ios ACTION=test SHARD_IDX=${{ matrix.idx }}
      - name: Upload artifacts
        uses: trinhngocthuyen/gh-actions/core/artifacts@main
        with:
          artifacts-upload-name: test
          artifacts-upload-path: examples/ios/DerivedData/Logs/Test

  coverage:
    runs-on: macos-12
    needs: test
    steps:
      - name: Install
        uses: trinhngocthuyen/gh-actions/py/install@main
      - name: Download artifacts
        uses: trinhngocthuyen/gh-actions/core/artifacts@main
        with:
          artifacts-download-name: test
          artifacts-download-path: examples/ios/DerivedData/Logs/Test
      - name: Makefile
        uses: trinhngocthuyen/gh-actions/core/makefile@main
        with:
          targets: install test.integration.ios ACTION=coverage
