name: integration-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'examples/ios/**'
      - 'scripts/**'

env:
  PYTHON_VERSION: '3.10'

jobs:
  build:
    runs-on: macos-12 # https://github.com/actions/virtual-environments (xcode 13.4.1)
    steps:
      - name: Install
        uses: trinhngocthuyen/gh-actions/py/install@main
      - name: Makefile
        uses: trinhngocthuyen/gh-actions/core/makefile@main
        with:
          targets: install test.integration.ios ACTION=build
      - name: Upload artifacts
        uses: trinhngocthuyen/gh-actions/core/artifacts@main
        with:
          artifacts-upload-name: build
          artifacts-upload-path: examples/ios/DerivedData/Build/Products

  ui_test:
    runs-on: macos-12
    needs: build
    strategy:
      matrix:
        idx: [1, 2]
    env:
      NUM_OF_SHARDS: 2
      SHARD_IDX: ${{ matrix.idx }}
      ACTION: test
      ONLY_TESTING: EXUITests
    steps:
      - name: Install
        uses: trinhngocthuyen/gh-actions/py/install@main
      - name: Download artifacts
        uses: trinhngocthuyen/gh-actions/core/artifacts@main
        with:
          artifacts-download-name: build
          artifacts-download-path: examples/ios/DerivedData/Build/Products
      - name: Makefile
        uses: trinhngocthuyen/gh-actions/core/makefile@main
        with:
          targets: install test.integration.ios
      - name: Upload artifacts
        uses: trinhngocthuyen/gh-actions/core/artifacts@main
        with:
          artifacts-upload-name: ui_test
          artifacts-upload-path: examples/ios/DerivedData/Logs/Test

  unit_test:
    runs-on: macos-12
    needs: build
    env:
       ACTION: test
       ONLY_TESTING: EXTests
    steps:
      - name: Install
        uses: trinhngocthuyen/gh-actions/py/install@main
      - name: Download artifacts
        uses: trinhngocthuyen/gh-actions/core/artifacts@main
        with:
          artifacts-download-name: build
          artifacts-download-path: examples/ios/DerivedData/Build/Products
      - name: Makefile
        uses: trinhngocthuyen/gh-actions/core/makefile@main
        with:
          targets: install test.integration.ios
      - name: Upload artifacts
        uses: trinhngocthuyen/gh-actions/core/artifacts@main
        with:
          artifacts-upload-name: unit_test
          artifacts-upload-path: examples/ios/DerivedData/Logs/Test

  cov:
    runs-on: macos-12
    needs: unit_test
    steps:
      - name: Install
        uses: trinhngocthuyen/gh-actions/py/install@main
      - name: Download artifacts
        uses: trinhngocthuyen/gh-actions/core/artifacts@main
        with:
          artifacts-download-name: unit_test
          artifacts-download-path: examples/ios/DerivedData/Logs/Test
      - name: Makefile
        uses: trinhngocthuyen/gh-actions/core/makefile@main
        with:
          targets: install test.integration.ios ACTION=cov
      - name: Upload artifacts
        uses: trinhngocthuyen/gh-actions/core/artifacts@main
        with:
          artifacts-upload-name: cov
          artifacts-upload-path: examples/ios/.artifacts/cov
