name: integration-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-12 # https://github.com/actions/virtual-environments (xcode 13.4.1)
    outputs:
      artifacts-name: ${{ steps.exec.outputs.artifacts-name }}
      artifacts-path: ${{ steps.exec.outputs.artifacts-path }}
    steps:
      - id: exec
        name: Exec
        uses: trinhngocthuyen/gh-action-py-exec@main
        with:
          checkout-submodules: true
          makefile-target: install test.integration.ios ACTION=build
          artifacts-upload-name: build
          artifacts-upload-path: integration_tests/DerivedData/Build/Products

  test:
    runs-on: macos-12
    needs: build
    strategy:
      matrix:
        idx: [1, 2]
    outputs:
      artifacts-name: ${{ steps.exec.outputs.artifacts-name }}
      artifacts-path: ${{ steps.exec.outputs.artifacts-path }}
    steps:
      - id: exec
        name: Exec
        uses: trinhngocthuyen/gh-action-py-exec@main
        with:
          checkout-submodules: true
          makefile-target: install test.integration.ios ACTION=test SHARD_IDX=${{ matrix.idx }}
          artifacts-download-name: build
          artifacts-download-path: integration_tests/DerivedData/Build/Products
          artifacts-upload-name: test
          artifacts-upload-path: |
            integration_tests/DerivedData/Logs/Test
            integration_tests/DerivedData/Build/ProfileData

  coverage:
    runs-on: macos-12
    needs: test
    steps:
      - id: exec
        name: Exec
        uses: trinhngocthuyen/gh-action-py-exec@main
        with:
          checkout-submodules: true
          makefile-target: install test.integration.ios ACTION=coverage
          artifacts-download-name: build
          artifacts-download-path: integration_tests/DerivedData/Build/Products
          artifacts-download-name-2: test
          artifacts-download-path-2: integration_tests/DerivedData
