name: lint

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: trinhngocthuyen/gh-action-py-exec@main
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
