name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  VERSION_SUFFIX: ".dev${{ github.run_id }}"

jobs:
  pytest:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: py38-ubuntu
            py_version: 3.8
          # - os: macOS-latest
          #   name: py38-mac
          #   py_version: 3.8

    steps:
      - name: Install
        uses: trinhngocthuyen/gh-action-py-install
        with:
          python-version: ${{ matrix.py_version }}
      - name: Test (py)
        run: make test.py

  integration_test_ios:
    runs-on: macOS-latest
    name: integration-ios
    steps:
      - name: Install
        uses: trinhngocthuyen/gh-action-py-install
        with:
          python-version: 3.8
      - name: Test (integration)
        run: make test.integration.ios
