name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: py38-ubuntu
            py_version: '3.8'
          - os: ubuntu-latest
            name: py39-ubuntu
            py_version: '3.9'
          - os: ubuntu-latest
            name: py310-ubuntu
            py_version: '3.10'
          # - os: macOS-latest
          #   name: py38-mac
          #   py_version: 3.8

    steps:
      - name: Install
        uses: trinhngocthuyen/gh-actions/py/install@main
        with:
          python-version: ${{ matrix.py_version }}
      - name: Makefile
        uses: trinhngocthuyen/gh-actions/core/makefile@main
        with:
          targets: install test.py
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests
